CREATE TABLE IF NOT EXISTS "signs" (
	`id`	INTEGER PRIMARY KEY,
	`X` INTEGER,
	`Y` INTEGER,
	`Z` INTEGER,
	`World` TEXT
);

CREATE TABLE IF NOT EXISTS "temptable" (
	`id`	INTEGER PRIMARY KEY,
	`X` INTEGER,
	`Y` INTEGER,
	`Z` INTEGER,
	`World` TEXT
);

INSERT INTO "temptable" SELECT DISTINCT * FROM "signs" GROUP BY `id`;

DROP TABLE "signs";
CREATE TABLE IF NOT EXISTS "signs" (
	`id`	INTEGER PRIMARY KEY,
	`X` INTEGER,
	`Y` INTEGER,
	`Z` INTEGER,
	`World` TEXT
);
INSERT INTO "signs" SELECT * FROM "temptable";
DROP TABLE "temptable"
